name: Publish to VSCode Marketplace

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: VSCE Publish
              run: npm install
            - uses: lannonbr/vsce-action@master
              with:
                  args: "publish -p $VSCE_TOKEN"
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
